version: 2

models:
  - name: stg_orders_ecomm
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers_ecomm')
              field: customer_id

      - name: status
        tests:
          - accepted_values:
              values: ['completed', 'returned', 'cancelled', 'processing', 'pending']

      - name: net_amount
        tests:
          - not_null
          - not_negative
          - between:
              min_value: 0
              max_value: 1000000

      - name: total_amount
        tests:
          - not_null:
              severity: warn
              where: "status = 'completed'"